depsets:
  - name: ray_base_test_depset
    operation: compile
    requirements:
      - requirements_test.txt
    constraints:
      - requirement_constraints_test.txt
    output: requirements_compiled.txt
  - name: general_depset
    operation: compile
    requirements:
      - requirements_test.txt
    output: requirements_compiled_general.txt
  - name: subset_base_test_depset
    operation: subset
    source_depset: ray_base_test_depset
    requirements:
      - requirement_constraints_subset.txt
    output: requirements_compiled_subset_base.txt
